# Generated by Django 4.2.8 on 2023-12-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Question',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Фамилия'),
        ),
    ]
